/* AUTH */
export const NEW_FAVORITE_WEATHER = "NEW_FAVORITE_WEATHER";
export const GET_FOVORITE_WEATHER = "GET_FOVORITE_WEATHER";
export const DELETE_FAVORITE_WEATHER = "DELETE_FAVORITE_WEATHER";
export const GET_ALL_FAVORITE_WEATHERS = "GET_ALL_FAVORITE_WEATHERS";

/* NO AUTH */
export const NEW_WEATHER = "NEW_WEATHER";
export const GET_WEATHER = "GET_WEATHER";
export const DELETE_WEATHER = "DELETE_WEATHER";
export const SET_WEATHER = "SET_WEATHER";

/* Coors */

export const SET_CURRENT_COORS = "SET_CURRENT_COORS";
